classdef HuboStateEncoder < LCMCoder
    properties
        defaultCoordinateNames
    end
    
    methods
        function obj = HuboStateEncoder(coordinateNames)
            obj.defaultCoordinateNames = coordinateNames;
            
        end
        
        function [x,t] = decode(obj,data)
            msg = hubo.hubo_hubo2state(data);
            if ~isempty(msg)
            x = [0,0,-0,04,0,0,0,...
                msg.NeckYaw,...
                msg.Neck1,...
                msg.Neck2,...
                msg.LeftShoulderPitch,...
                msg.LeftShoulderRoll,...
                msg.LeftShoulderYaw,...
                msg.LeftElbowPitch,...
                msg.LeftWristYaw,...
                msg.LeftWristPitch,...
                msg.RightShoulderPitch,...
                msg.RightShoulderRoll,...
                msg.RightShoulderYaw,...
                msg.RightElbowPitch,...
                msg.RightWristYaw,...
                msg.RightWristPitch,...
                msg.TrunkYaw,...
                msg.LeftHipYaw,...
                msg.LeftHipRoll,...
                msg.LeftHipPitch,...
                msg.LeftKneePitch,...
                msg.LeftAnklePitch,...
                msg.LeftAnkleRoll,...
                msg.RightHipYaw,...
                msg.RightHipRoll,...
                msg.RightHipPitch,...
                msg.RightKneePitch,...
                msg.RightAnklePitch,...
                msg.RightAnkleRoll,...
                0,0,0,0,0,0,...
                msg.NeckYawdot,...
                msg.Neck1dot,...
                msg.Neck2dot,...
                msg.LeftShoulderPitchdot,...
                msg.LeftShoulderRolldot,...
                msg.LeftShoulderYawdot,...
                msg.LeftElbowPitchdot,...
                msg.LeftWristYawdot,...
                msg.LeftWristPitchdot,...
                msg.RightShoulderPitchdot,...
                msg.RightShoulderRolldot,...
                msg.RightShoulderYawdot,...
                msg.RightElbowPitchdot,...
                msg.RightWristYawdot,...
                msg.RightWristPitchdot,...
                msg.TrunkYawdot,...
                msg.LeftHipYawdot,...
                msg.LeftHipRolldot,...
                msg.LeftHipPitchdot,...
                msg.LeftKneePitchdot,...
                msg.LeftAnklePitchdot,...
                msg.LeftAnkleRolldot,...
                msg.RightHipYawdot,...
                msg.RightHipRolldot,...
                msg.RightHipPitchdot,...
                msg.RightKneePitchdot,...
                msg.RightAnklePitchdot,...
                msg.RightAnkleRolldot,...
                ];
                t = msg.timestamp;
            end
        end
        function dimmatrix = dim(obj)
            dimmatrix = 68;
        end
        function msg = encode(obj,t,x)
            msg = hubo.hubo_hubo2state();
            msg.timestamp = t;
            msg.NeckYaw = x(7);
            msg.Neck1 = x(8);
            msg.Neck2 = x(9);
            msg.LeftShoulderPitch = x(10);
            msg.LeftShoulderRoll = x(11);
            msg.LeftShoulderYaw = x(12);
            msg.LeftElbowPitch = x(13);
            msg.LeftWristYaw = x(14);
            msg.LeftWristPitch = x(15);
            msg.RightShoulderPitch = x(16);
            msg.RightShoulderRoll = x(17);
            msg.RightShoulderYaw = x(18);
            msg.RightElbowPitch = x(19);
            msg.RightWristYaw = x(20);
            msg.RightWristPitch = x(21);
            msg.TrunkYaw = x(22);
            msg.LeftHipYaw = x(23);
            msg.LeftHipRoll = x(24);
            msg.LeftHipPitch = x(25);
            msg.LeftKneePitch = x(26);
            msg.LeftAnklePitch = x(27);
            msg.LeftAnkleRoll = x(28);
            msg.RightHipYaw = x(29);
            msg.RightHipRoll = x(30);
            msg.RightHipPitch = x(31);
            msg.RightKneePitch = x(32);
            msg.RightAnklePitch = x(33);
            msg.RightAnkleRoll = x(34);
        end
        function name = timestampName(obj) 
            name = 'timestamp';
        end
        function name = coordinateNames(obj)
            name = obj.defaultCoordinateNames;
%             strArray = java_array('java.lang.String', obj.dim());
%             for i=1:obj.dim()
%                 strArray(i) = java.lang.String('');
%             end
%             name = cell(strArray);
%                 'NeckYaw'
%                 'Neck1',...
%                 'Neck2',...
%                 'LeftShoulderPitch',...
%                 'LeftShoulderRoll',...
%                 'LeftShoulderYaw',...
%                 'LeftElbowPitch',...
%                 'LeftWristYaw',...
%                 'LeftWristPitch',...
%                 'RightShoulderPitch',...
%                 'RightShoulderRoll',...
%                 'RightShoulderYaw',...
%                 'RightElbowPitch',...
%                 'RightWristYaw',...
%                 'RightWristPitch',...
%                 'TrunkYaw',...
%                 'LeftHipYaw',...
%                 'LeftHipRoll',...
%                 'LeftHipPitch',...
%                 'LeftKneePitch',...
%                 'LeftAnklePitch',...
%                 'LeftAnkleRoll',...
%                 'RightHipYaw',...
%                 'RightHipRoll',...
%                 'RightHipPitch',...
%                 'RightKneePitch',...
%                 'RightAnklePitch',...
%                 'RightAnkleRoll',...
%                 'NeckYawdot',...
%                 'Neck1dot',...
%                 'Neck2dot',...
%                 'LeftShoulderPitchdot',...
%                 'LeftShoulderRolldot',...
%                 'LeftShoulderYawdot',...
%                 'LeftElbowPitchdot',...
%                 'LeftWristYawdot',...
%                 'LeftWristPitchdot',...
%                 'RightShoulderPitchdot',...
%                 'RightShoulderRolldot',...
%                 'RightShoulderYawdot',...
%                 'RightElbowPitchdot',...
%                 'RightWristYawdot',...
%                 'RightWristPitchdot',...
%                 'TrunkYawdot',...
%                 'LeftHipYawdot',...
%                 'LeftHipRolldot',...
%                 'LeftHipPitchdot',...
%                 'LeftKneePitchdot',...
%                 'LeftAnklePitchdot',...
%                 'LeftAnkleRolldot',...
%                 'RightHipYawdot',...
%                 'RightHipRolldot',...
%                 'RightHipPitchdot',...
%                 'RightKneePitchdot',...
%                 'RightAnklePitchdot',...
%                 'RightAnkleRolldot',...
%                 ];
        end
    end

end
